# Weather4cast 2023 Benchmark
# Transfer Learning configuration file

# Dataset parameters
dataset:
  data_root: "../data"
  regions: ["roxi_0008", "roxi_0009", "roxi_0010"]  # Transfer learning regions
  year: 2019
  in_seq_len: 4
  out_seq_len: 32  # 32 for 8-hour prediction, 16 for 4-hour prediction
  sat_channels: ["IR_016", "IR_039", "IR_087", "IR_097", "IR_108", "IR_120", "IR_134", "VIS006", "VIS008", "WV_062", "WV_073"]
  normalize: true

# Model parameters
model:
  in_channels: 44  # 11 channels * 4 time steps
  out_channels: 32  # 32 time steps for 8-hour prediction
  init_features: 64
  depth: 4
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"

# Training parameters
train:
  batch_size: 16
  learning_rate: 0.00005  # Lower learning rate for transfer learning
  max_epochs: 50  # Fewer epochs for transfer learning
  n_workers: 4
  early_stopping: true
  patience: 5  # Lower patience for transfer learning

# Experiment parameters
experiment:
  name: "transfer_learning"
  experiment_folder: "lightning_logs"
  sub_folder: "weather4cast"
  logging: true
  precision: 32
  plot_results: false
  in_channel_to_plot: 4  # IR_108 channel

# Prediction parameters
predict:
  region_to_predict: "roxi_0008"  # Change this for different transfer regions
  year_to_predict: 2019 