name: erasing_invisible_watermarks
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pytorch
  - torchvision
  - pillow
  - tqdm
  - pip:
    - scikit-image
    - matplotlib
    - requests
    - torchmetrics>=0.11.0
    - lpips
    - git+https://github.com/openai/CLIP.git  # Use OpenAI's CLIP directly
    - timm
    - ftfy  # Required for CLIP
    - regex  # Required for CLIP
    - ldm  # Required for VAE
  - pip:
    - scikit-image
    - matplotlib
    - requests
    - torchmetrics>=0.11.0
    - lpips
    - clip
    - timm  # For FID calculation 