name: perception_temporal_sound_localisation
channels:
  - defaults
dependencies:
  - python=3.11
  - pybind11
  - requests
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - tensorboard
    - h5py
    - scipy
    - pandas
    - joblib
    - pyyaml