name: weather4cast-2023
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - torchvision
  - pytorch-lightning=2.0.0
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - h5py
  - pyyaml
  - pip
  - pip:
    - einops
    - timm 